# **Лабораторна робота №2А**
---
## Послідовність виконання лабораторної роботи:
#### 1. Переглянув офіційну документацію для ***Python***.
#### 2. Створюю файл ***test.py*** для виконання базових прикладів.
1. Виводжу вбудованні константи за допомогою команд:

    ```python
    print("Перша константа", False)
    print("Друга константа", True)
    print("Третя константа", None)
    ```
1. Виводжу результат роботи вбудованих функцій за допомогою команд:
   ```python
    print("3 в 3 степені дорівнює: ", pow(3,3))
    print("Число 4 в вісімковій системі числення дорівнює: ", oct(4))
    print("Мінімальне число з чисел 1,29,4,5: ",min(1,29,4,5))
    ```
1. Виводжу результат роботи циклу і розгалужень за допомогою команд:
    ```python
    x= [5 for i in range(25)]
    print("Виведення 25 п'ятірок з масиву: ",x)
    
    a = 15
    print("Змінна 'a' дорівнює 15" if a == 15 else "Змінна 'a' не дорівнює 15")
    ```
1. Виводжу результат роботи конструкції `try`->`except`->`finally` при помилці за допомогою команд:
    ```python
    y=[545]
    print("Що буде якщо вивести [555] елемент масиву y[]?: ")
    try:
        print(y[555])
    except Exception as e:
        print(e)
    finally:
        print("То ось що буде!")
    print("")
    ```
1. Виводжу результат роботи контекст-менеджера `with` за допомогою команд:
    ```python
    i=1
    with open("lab2a_1.py", "r") as f:
        for line in f:
            print("Line " + str(i) + ": " + line)
            i=i+1
    ```
1. Виводжу результат роботи з `lambdas` за допомогою команд:
    ```python
    _lambda = lambda f_number, s_number: f'Сума першого і другого числа дорівнює {f_number + s_number}'
    print("Розташування функції в памяті: ", _lambda)
    print("Виклик лямбди: ", _lambda(10, 15))
    ```
#### 3. Створив у власному репозиторії такі файли:
   ```text
   lab2a/
   ├── modules/
   │   └── common.py
   ├── __init__.py
   └── __main__.py
   ```
1. Перейшовши у папку з даними файлами запустив виконання програми цією командою:

    ```sh
    python3 .
    ```
    Виконання команди:
    ```text
    PS D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a> python D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a
    We are in the __main__
    2021-10-21 22:43:46.898931
    win32
    test
    ```
1. Після запуску команди `python ` програма в першому рядку виводить назву файла який виконувався, в другому рядку виводиться час і дата виконання даної програми, в третьому рядку виводиться ос на якій було запущено програму і в четвертому рядку виведено текст "test".

    a. Після запуску команди: `python -h` в консоль виводиться інформація про додаткові параметри та їх використання. Результат виконання команди:
    ```text
    PS D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a> python D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a -h
    usage: lab2a [-h] [-o OPT] [-l]
    
    Приклад передачі аргументів у Python програму.
    
    optional arguments:
      -h, --help            show this help message and
                            exit
      -o OPT, --optional OPT
                            Цей параметр є вибірковим.
      -l, --logs            Якщо виконати команду з цим
                            параметром будуть виводитись
                            логи.
    ```
    
    b. Після запуску команди: `python -o "Цей текст також має вивестись"` в консоль виводиться інформація така сама як і в пункті 2. тільки додається текст про те що з консолї було передано аргумент і саме повідомлення яке ми передаємо. Результат виконання команди:
    ```text
    PS D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a> python D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a -o "Цей текст також має вивестись"
    We are in the __main__
    2021-10-21 22:47:12.307836
    win32
    З консолі було передано аргумент
     ========== >> Цей текст також має вивестись << ==========
    test 
    ```
    c. Детально ознайомився з аргументами.
    d. Ознайомився з логуванням і запустив команду `python --logs`.
    Результат виконання команди:
    ```text
    PS D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a> python D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a --logs
    2021-10-21 22:47:59,047 root INFO: Тут буде просто інформативне повідомлення
    2021-10-21 22:47:59,047 root WARNING: Це Warning повідомлення
    2021-10-21 22:47:59,047 root ERROR: Це повідомлення про помилку
    test
    ```
1. Створив власну функцію у файлі `common.py` яка буде виводить всі парні числа від 0 до 100,  якщо у функцію передати значення True і непарні якщо значення False. Виклик цієї функцію виконую з `__main__` .
Код власної функції:
    ```python
    def filter_numbers(filter):
    numbers=range(0,101)
    if filter=="True":
        msg = "Парні елементи: " 
    elif filter=="False":
        msg = "Непарні елементи: "
    
    for index in range(0, len(numbers)):
        if (filter == "True") & (numbers[index]%2 == 0):
            msg += str(numbers[index]) + " "
        elif (filter == "False") & (numbers[index]%2 != 0):
            msg += str(numbers[index]) + " "
    return msg
    ```
    Результат виконання з параметром `-o True`:
    ```text
    PS D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a> python D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a -o True
    We are in the __main__
    2021-10-21 22:49:10.271840
    win32
    Парні елементи: 0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100
    З консолі було передано аргумент
     ========== >> True << ==========
    test
    ```
    Результат виконання з параметром `-o False`:
    ```text
    PS D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a> python D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a -o False
    We are in the __main__
    2021-10-21 22:49:48.718884
    win32
    Непарні елементи: 1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99
    З консолі було передано аргумент
     ========== >> False << ==========
    test
    ```
1. Створив функцію яка може виконуватись з помилкою. У випадку її виникнення виводить `ERROR` повідомлення за допомогою логування використовуючи бібліотеку `logging`. Якщо функція виконалася без помилки то виводить `INFO` повідомлення.
Код власної функції:
    ```python
    def show_array():
    x=[random.randint(0, 15) for i in range(10)]      
    print("Масив X[]:", x)
    index = int(input("Введіть номер елемента масиву який хочете вивести: "))
    try:
        print(f"X[{index}] = {x[index]}")
    except IndexError:
        logging.error("Ви ввели число за межами проміжку 0-3")
    else:
        logging.info("Ви ввели коректні дані")
    ```
    Результат виконання з помилкою:
    ```text
    PS D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a> python    D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a
    We are in the __main__
    2021-10-21 22:51:43.025837
    win32
    Масив X[]: [14, 2, 0, 1, 13, 6, 11, 4, 14, 12]
    Введіть номер елемента масиву який хочете вивести: 25
    2021-10-21 22:51:47,578 root ERROR: Ви ввели число за межами проміжку 0-3
    test
    ```
    Результат виконання без помилки:
    ```text
    PS D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a> python D:\Labs\3\devops_course\2021\IK-31\Pryhoda_Andriy_IK_31\lab2a
    We are in the __main__
    2021-10-21 22:50:58.314930
    win32
    Масив X[]: [14, 13, 7, 4, 11, 9, 2, 13, 13, 12]
    Введіть номер елемента масиву який хочете вивести: 2
    X[2] = 7
    2021-10-21 22:51:03,307 root INFO: Ви ввели коректні дані
    test
    ```